### ISSUE TITLE
Support prismatic joints

### ISSUE THREAD

**Issue by traversaro** [ami-iit/ADAM#28]
For the goals of one of our internal projects, it would be convenient if ADAM supported prismatic joints. 

cc @Giulero

**Comment by DanielePucci** [comment]
CC @CarlottaSartore

**Comment by Giulero** [comment]
It shouldn't be difficult. I'll do it!

**Comment by CarlottaSartore** [comment]
In the past, I worked on it (see for instance https://github.com/ami-iit/ADAM/compare/main...CarlottaSartore:ADAM:add_joint_type_param), I can try to make a minimum invasive PR only with the modification for supporting the prismatic joint. 

For the time being, I would disregard the hardware parameters since it brings with it the problem of the modality in which the joint origin should be moved  (see https://github.com/ami-iit/element_hardware-intelligence/issues/72)

**Comment by traversaro** [comment]
Thanks @Giulero @CarlottaSartore ! I think @VenusPasandi was also interested in working on this, so probably you can coordinate.

**Comment by Giulero** [comment]
Created a PR for this. I used the code @CarlottaSartore  implemented in a previous PR <3

I also might need an urdf of a robot with prismatic joints.
